= OpenShift Performance Benchmarking Guide
:navtitle: Home

== Introduction

Course Title: OpenShift performance benchmarking

Description: This intensive, hands-on course will teach you how to use the built-in monitoring stack and Kubernetes-native tools like kube-burner to stress-test your cluster's networking and control plane. We'll dive into establishing performance baselines, finding bottlenecks before they become problems, and getting the data you need to keep your platform running smoothly and efficiently.

Duration: 4-8 hours

== Objectives

On completing this course, you should gain skills to proactively measure, analyze, and tune an OpenShift cluster for optimal performance:

 - Articulate performance goals
 - Identify bottlenecks
 - Get familiar with Kubernetes-native benchmarking tools
 - Establish a baseline
 - Benchmark the data plane
 - Stress-Test the control plane
 - Analytical and reporting abilities


== Prerequisites

This course assumes that you have the following prior experience:

 - Basic understanding of containerization (Docker, Podman) and Kubernetes/OpenShift concepts.
 - Familiarity with the Linux command line.
 - Experience with basic OpenShift administration is beneficial but not required.

