= Lab Environment Setup

== Instructions to Launch Your Lab on the Red Hat Demo Platform (RHDP)

. **Log in** to the xref:#RHDP-Portal-Links[RHDP portal]
. **Search** for the catalog entry: **OpenShift Perf and Scale Benchmarking**.
. **Click** on the catalog entry in the search results.
. On the catalog page, **click** the **Order** button.
. **Fill out** the required details in the order form.
. **Review the warning** at the bottom of the form and **check the box** labeled: +
   *“I confirm that I understand the above warnings.”*
. **Click** the **Order** button to place your lab order.

=== Important Notes:
- This lab may take approximately **FIXME minutes** to become ready.
- You will receive an **email with access details** once your lab environment is ready.
- You can also **retrieve lab access** directly from the RHDP portal.

=== How to Access Your Lab via the RHDP Portal:
. On the RHDP portal, **click** on the **Services** option in the left-hand menu.
. **Select your lab** from the listings on the right-hand side of the page to view access details.

[[RHDP-Portal-Links]]
=== RHDP Portal Links
- RedHat associates: https://demo.redhat.com/[https://demo.redhat.com/,window=_blank]
- RedHat partners: https://partner.demo.redhat.com/[https://partner.demo.redhat.com/,window=_blank]

== Validate the Lab environment

Let's make sure the environment healthy and ready to continue with the training:
```bash
oc get node
oc get co
```

Let's make sure the ES instance that we need to index the benchmarking results through the course is available and responsive:
```bash
# Get password
PASSWORD=$(oc get secret elasticsearch-es-elastic-user -n openshift-logging -o jsonpath='{.data.elastic}' | base64 -d)

# Check cluster health
oc exec -n openshift-logging elasticsearch-es-default-0 -- curl -k -u elastic:$PASSWORD https://elasticsearch-es-http.openshift-logging.svc.cluster.local:9200/_cluster/health?pretty
```